// local development
@port = 5085

// docker
// @port = 8080

POST http://localhost:{{port}}/transferencias
Content-Type: application/json

{
    "clienteIdDe": "726f6db7-2407-499b-986b-f7d6113cfdae",
    "clienteIdPara": "5c6cdc79-dd4c-4dbd-86fe-c8f8d807ad19",
    "valor" : 2304893.23
}
