services:
  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bacen
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"
  
  bacen:
    image: bacen
    hostname: bacen
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: bacen
