services:
  bacen:
    image: bacen
    hostname: bacen
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits: # média
          cpus: "0.5"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: bacen
