services:
  banquo:
    image: banquo:latest
    hostname: banquo
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=banquo
      - BACEN_API_URL=http://bacen:8080/transferencias
    ports:
      - "9999:8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - default
      - bacen
    deploy:
      resources:
        limits: # pequena
          cpus: "0.3"
          memory: "50MB"

  db:
    image: postgres:17.0
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=banquo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    deploy:
      resources:
        limits: # pequena
          cpus: "0.3"
          memory: "50MB"

networks:
  default:
    driver: bridge
  bacen:
    external: true
