services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=secomp
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #command: postgres -c max_connections=4
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "440MB"

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"

networks:
  default:
    driver: bridge
    name: secomp-2024
