services:
  banquo:
    image: secomp-design-01-banquo:latest
    hostname: banquo
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=banquo
      - BACEN_API_URL=http://bacen:8080/transferencias
    ports:
      - "8080:8080"
    depends_on:
      - db
      - bacen
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=banquo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200MB"

  bacen:
    image: secomp-design-01-bacen:latest
    hostname: bacen
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: secomp-2024
