services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - banquo
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "30MB"

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"

  banquo:
    image: secomp-design-01-banquo:latest
    hostname: banquo
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=banquo
      - BACEN_API_URL=http://bacen:8080/transferencias
    depends_on:
      - db
      - bacen
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=banquo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200MB"

  bacen:
    image: secomp-design-01-bacen:latest
    hostname: bacen
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: secomp-2024
