services:
  load.balancer:
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - banquo
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

  banquo:
    image: banquo
    hostname: banquo
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=banquo
      - BACEN_API_URL=http://bacen:8080/transferencias
    depends_on:
      - db
    restart: on-failure
    networks:
      - default
      - bacen
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  db:
    image: postgres:17.0
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=banquo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  default:
    driver: bridge
  bacen:
    external: true
